In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("papers_data_from_rcrossref_Arabic world.csv" , index_col=0)
data.head()

C:\Users\Sohaila\AppData\Local\Temp\ipykernel_23568\2973931704.py:1: DtypeWarning: Columns (5,21,23,24,25,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("papers_data_from_rcrossref_Arabic world.csv" , index_col=0)

,Unnamed: 0,container.title,created,deposited,published.print,doi,indexed,issued,member,prefix,...,type,url,author,link,reference,issn,issue,volume,page,language
Unnamed: 0.1,,,,,,,,,,,,,,,,,,,,,
0.0,1,Race,2008-03-29,2021-01-24,1965-04,10.1177/030639686500600401,2022-04-03,1965-04,179,10.1177,...,journal-article,http://dx.doi.org/10.1177/030639686500600401,"[{""given"":""Patrick"",""family"":""Duncan"",""sequenc...","c(""http://journals.sagepub.com/doi/pdf/10.1177...","[{""key"":""atypb1"",""volume.title"":""House of Asse...",NaN,NaN,NaN,NaN,NaN
2.0,3,The Journal of Chemical Physics,2004-02-04,2024-02-09,1969-01-15,10.1063/1.1671082,2024-02-09,1969-01-15,317,10.1063,...,journal-article,http://dx.doi.org/10.1063/1.1671082,"[{""given"":""J."",""family"":""Fourny"",""sequence"":""f...","c(""https://pubs.aip.org/aip/jcp/article-pdf/50...","[{""key"":""2024020904355486600_r1""},{""key"":""2024...",NaN,NaN,NaN,NaN,NaN
3.0,4,Journal of Mathematical Physics,2004-02-10,2024-02-07,1970-07-01,10.1063/1.1665375,2024-07-02,1970-07-01,317,10.1063,...,journal-article,http://dx.doi.org/10.1063/1.1665375,"[{""given"":""B."",""family"":""Picinbono"",""sequence""...","c(""https://pubs.aip.org/aip/jmp/article-pdf/11...","[{""key"":""2024020706263321400_r1""},{""key"":""2024...",NaN,NaN,NaN,NaN,NaN
5.0,6,Journal of Palestine Studies,2012-09-12,2021-02-13,1971-10-01,10.2307/2535999,2022-04-03,1971-10-01,301,10.1080,...,journal-article,http://dx.doi.org/10.2307/2535999,"[{""given"":""William B."",""family"":""Quandt"",""sequ...","c(""http://online.ucpress.edu/jps/article-pdf/1...","[{""key"":""CIT0001"",""unstructured"":""New York Tim...",NaN,NaN,NaN,NaN,NaN
7.0,8,Annals of Clinical Biochemistry: International...,2014-02-05,2022-03-25,1978-01,10.1177/000456327801500135,2022-03-31,1978-01,179,10.1177,...,journal-article,http://dx.doi.org/10.1177/000456327801500135,"[{""given"":""D."",""family"":""Allard"",""sequence"":""f...","c(""http://journals.sagepub.com/doi/pdf/10.1177...","[{""key"":""bibr1-000456327801500135"",""first.page...",NaN,NaN,NaN,NaN,NaN

In [3]:
print(data["title"])

Unnamed: 0.1
0.0                  Is apartheid an Insoluble Problem ?
2.0    High-Temperature Dependence of Electron and Ho...
3.0                             Photoelectron Shot Noise
5.0     The Middle East Conflict in US Strategy, 1970-71
7.0    Assay of Tissue Free Cystine: Application to t...
                             ...
NaN    A new method for ecologists to estimate hetero...
NaN    Design of Three-Dimensional-Printed Compressio...
NaN    Host-associated helminth diversity and microbi...
NaN    PHA4GE quality control contextual data tags: s...
NaN    Trends in volumes and survival after hematopoi...
Name: title, Length: 493876, dtype: object

In [3]:
data.columns

Index(['Unnamed: 0', 'container.title', 'created', 'deposited',
       'published.print', 'doi', 'indexed', 'issued', 'member', 'prefix',
       'publisher', 'score', 'source', 'reference.count', 'references.count',
       'is.referenced.by.count', 'title', 'type', 'url', 'author', 'link',
       'reference', 'issn', 'issue', 'volume', 'page', 'language'],
      dtype='object')

In [4]:
data = data.drop(columns = ["Unnamed: 0"])

In [5]:
data.columns

Index(['container.title', 'created', 'deposited', 'published.print', 'doi',
       'indexed', 'issued', 'member', 'prefix', 'publisher', 'score', 'source',
       'reference.count', 'references.count', 'is.referenced.by.count',
       'title', 'type', 'url', 'author', 'link', 'reference', 'issn', 'issue',
       'volume', 'page', 'language'],
      dtype='object')

In [6]:
data_cleaned_pd = data.drop_duplicates(subset="doi")

In [8]:
print(len(data_cleaned_pd))
print(len(data))

333260
493876

In [9]:
data_cleaned_pd.to_csv("papers_data_from_rcrossref_Arabic world_cleaned.csv")

In [11]:
data_cleaned_read_pd = pd.read_csv("papers_data_from_rcrossref_Arabic world_cleaned.csv")
data_cleaned_read_pd.head()

C:\Users\Sohaila\AppData\Local\Temp\ipykernel_32084\4057336427.py:1: DtypeWarning: Columns (4,20,22,23,24,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  data_cleaned_read_pd = pd.read_csv("papers_data_from_rcrossref_Arabic world_cleaned.csv")

,Unnamed: 0.1,container.title,created,deposited,published.print,doi,indexed,issued,member,prefix,...,type,url,author,link,reference,issn,issue,volume,page,language
0,0.0,Race,2008-03-29,2021-01-24,1965-04,10.1177/030639686500600401,2022-04-03,1965-04,179,10.1177,...,journal-article,http://dx.doi.org/10.1177/030639686500600401,"[{""given"":""Patrick"",""family"":""Duncan"",""sequenc...","c(""http://journals.sagepub.com/doi/pdf/10.1177...","[{""key"":""atypb1"",""volume.title"":""House of Asse...",NaN,NaN,NaN,NaN,NaN
1,2.0,The Journal of Chemical Physics,2004-02-04,2024-02-09,1969-01-15,10.1063/1.1671082,2024-02-09,1969-01-15,317,10.1063,...,journal-article,http://dx.doi.org/10.1063/1.1671082,"[{""given"":""J."",""family"":""Fourny"",""sequence"":""f...","c(""https://pubs.aip.org/aip/jcp/article-pdf/50...","[{""key"":""2024020904355486600_r1""},{""key"":""2024...",NaN,NaN,NaN,NaN,NaN
2,3.0,Journal of Mathematical Physics,2004-02-10,2024-02-07,1970-07-01,10.1063/1.1665375,2024-07-02,1970-07-01,317,10.1063,...,journal-article,http://dx.doi.org/10.1063/1.1665375,"[{""given"":""B."",""family"":""Picinbono"",""sequence""...","c(""https://pubs.aip.org/aip/jmp/article-pdf/11...","[{""key"":""2024020706263321400_r1""},{""key"":""2024...",NaN,NaN,NaN,NaN,NaN
3,5.0,Journal of Palestine Studies,2012-09-12,2021-02-13,1971-10-01,10.2307/2535999,2022-04-03,1971-10-01,301,10.1080,...,journal-article,http://dx.doi.org/10.2307/2535999,"[{""given"":""William B."",""family"":""Quandt"",""sequ...","c(""http://online.ucpress.edu/jps/article-pdf/1...","[{""key"":""CIT0001"",""unstructured"":""New York Tim...",NaN,NaN,NaN,NaN,NaN
4,7.0,Annals of Clinical Biochemistry: International...,2014-02-05,2022-03-25,1978-01,10.1177/000456327801500135,2022-03-31,1978-01,179,10.1177,...,journal-article,http://dx.doi.org/10.1177/000456327801500135,"[{""given"":""D."",""family"":""Allard"",""sequence"":""f...","c(""http://journals.sagepub.com/doi/pdf/10.1177...","[{""key"":""bibr1-000456327801500135"",""first.page...",NaN,NaN,NaN,NaN,NaN

In [12]:
num_unique_doi = len(data_cleaned_read_pd["doi"].unique())
print(num_unique_doi)

333260

In [15]:
data_cleaned_read_pd.columns

Index(['Unnamed: 0.1', 'container.title', 'created', 'deposited',
       'published.print', 'doi', 'indexed', 'issued', 'member', 'prefix',
       'publisher', 'score', 'source', 'reference.count', 'references.count',
       'is.referenced.by.count', 'title', 'type', 'url', 'author', 'link',
       'reference', 'issn', 'issue', 'volume', 'page', 'language'],
      dtype='object')

In [16]:
data_cleaned_read_pd = data_cleaned_read_pd.drop(columns = ["Unnamed: 0.1"])

In [17]:
data_cleaned_read_pd.columns

Index(['container.title', 'created', 'deposited', 'published.print', 'doi',
       'indexed', 'issued', 'member', 'prefix', 'publisher', 'score', 'source',
       'reference.count', 'references.count', 'is.referenced.by.count',
       'title', 'type', 'url', 'author', 'link', 'reference', 'issn', 'issue',
       'volume', 'page', 'language'],
      dtype='object')

In [18]:
nulls = data_cleaned_read_pd.isnull().sum()
print(nulls)

container.title              918
created                        0
deposited                      0
published.print            90786
doi                            0
indexed                        0
issued                         0
member                         0
prefix                         0
publisher                      0
score                          0
source                         0
reference.count                0
references.count               0
is.referenced.by.count         0
title                          0
type                           0
url                            0
author                         0
link                       96295
reference                      0
issn                      237817
issue                     249252
volume                    241466
page                      315475
language                  317924
dtype: int64

## some failures with cleaning of data using AWK

In [ ]:
with open("file_uniq.csv", "r") as file:
    lines = file.readlines()
    print(lines[479])  # Python is zero-indexed; line 480 is lines[479]
    print(len())

851.0,852,The Journal of Physical Chemistry B,2006-10-07,2021-10-19,2006-11-01,10.1021/jp061607q,2023-09-13,2006-10-07,316,10.1021,American Chemical Society (ACS),10.185406,Crossref,33,33,7,Characterization of Counterion and Surface Influence on Micelle Formation Using Tapping Mode Atomic Force Microscopy in Air,journal-article,http://dx.doi.org/10.1021/jp061607q,"[{""given"":""Lila"",""family"":""Chaal"",""sequence"":""first"",""affiliation.name"":""UPR 15 CNRS Interfaces et Systèmes Electrochimiques, University P. et M. Curie, 4 Place Jussieu, 75252 Paris Cédex 05, France, and Laboratory Electrochimie et Corrosion, Department Génie des Procédés, University A Mira-Béjaia, Algeria""},{""given"":""Françoise"",""family"":""Pillier"",""sequence"":""additional"",""affiliation.name"":""UPR 15 CNRS Interfaces et Systèmes Electrochimiques, University P. et M. Curie, 4 Place Jussieu, 75252 Paris Cédex 05, France, and Laboratory Electrochimie et Corrosion, Department Génie des Procédés, University A Mira-Béjaia, Algeria""},{""given"":""Boualem"",""family"":""Saidani"",""sequence"":""additional"",""affiliation.name"":""UPR 15 CNRS Interfaces et Systèmes Electrochimiques, University P. et M. Curie, 4 Place Jussieu, 75252 Paris Cédex 05, France, and Laboratory Electrochimie et Corrosion, Department Génie des Procédés, University A Mira-Béjaia, Algeria""},{""given"":""Suzanne"",""family"":""Joiret"",""sequence"":""additional"",""affiliation.name"":""UPR 15 CNRS Interfaces et Systèmes Electrochimiques, University P. et M. Curie, 4 Place Jussieu, 75252 Paris Cédex 05, France, and Laboratory Electrochimie et Corrosion, Department Génie des Procédés, University A Mira-Béjaia, Algeria""},{""given"":""Alain"",""family"":""Pailleret"",""sequence"":""additional"",""affiliation.name"":""UPR 15 CNRS Interfaces et Systèmes Electrochimiques, University P. et M. Curie, 4 Place Jussieu, 75252 Paris Cédex 05, France, and Laboratory Electrochimie et Corrosion, Department Génie des Procédés, University A Mira-Béjaia, Algeria""},{""given"":""Claude"",""family"":""Deslouis"",""sequence"":""additional"",""affiliation.name"":""UPR 15 CNRS Interfaces et Systèmes Electrochimiques, University P. et M. Curie, 4 Place Jussieu, 75252 Paris Cédex 05, France, and Laboratory Electrochimie et Corrosion, Department Génie des Procédés, University A Mira-Béjaia, Algeria""}]","https://pubs.acs.org/doi/pdf/10.1021/jp061607q, unspecified, vor, similarity-checking","[{""key"":""jp061607qb00001/jp061607qb00001_1"",""first.page"":""359"",""volume"":""39"",""author"":""Lin Z."",""year"":""2000"",""journal.title"":""Rheol. Acta""},{""key"":""jp061607qb00002/jp061607qb00002_1"",""first.page"":""16"",""volume"":""14"",""author"":""Lu B."",""year"":""1998"",""journal.title"":""Langmuir"",""doi.asserted.by"":""crossref"",""DOI"":""10.1021/la971227j""},{""key"":""jp061607qb00003/jp061607qb00003_1"",""first.page"":""4413"",""volume"":""10"",""author"":""Manne S."",""year"":""1994"",""journal.title"":""Langmuir"",""doi.asserted.by"":""crossref"",""DOI"":""10.1021/la00024a003""},{""key"":""jp061607qb00004/jp061607qb00004_1"",""first.page"":""1482"",""volume"":""270"",""author"":""Manne S."",""year"":""1995"",""journal.title"":""Science"",""doi.asserted.by"":""crossref"",""DOI"":""10.1126/science.270.5241.1480""},{""key"":""jp061607qb00005/jp061607qb00005_1"",""first.page"":""4228"",""volume"":""13"",""author"":""Wanless E. J."",""year"":""1997"",""journal.title"":""Langmuir""},{""key"":""jp061607qb00006/jp061607qb00006_1"",""first.page"":""1384"",""volume"":""13"",""author"":""Jaschke M."",""year"":""1997"",""journal.title"":""Langmuir"",""doi.asserted.by"":""crossref"",""DOI"":""10.1021/la9607767""},{""key"":""jp061607qb00007/jp061607qb00007_1"",""first.page"":""1692"",""volume"":""15"",""author"":""Patrick H. N."",""year"":""1999"",""journal.title"":""Langmuir"",""doi.asserted.by"":""crossref"",""DOI"":""10.1021/la981612o""},{""key"":""jp061607qb00008/jp061607qb00008_1"",""first.page"":""168"",""volume"":""15"",""author"":""Ducker W. A."",""year"":""1999"",""journal.title"":""J. Langmuir"",""doi.asserted.by"":""crossref"",""DOI"":""10.1021/la9710942""},{""key"":""jp061607qb00009/jp061607qb00009_1"",""first.page"":""4454"",""volume"":""16"",""author"":""Subramanian V."",""year"":""2000"",""journal.title"":""Langmuir"",""doi.asserted.by"":""crossref"",""DOI"":""10.1021/la991245w""},{""key"":""jp061607qb00010/jp061607qb00010_1"",""first.page"":""1820"",""volume"":""17"",""author"":""Sakai H."",""year"":""2001"",""journal.title"":""Langmuir""},{""key"":""jp061607qb00011/jp061607qb00011_1"",""first.page"":""9"",""volume"":""68"",""author"":""Teschke O."",""year"":""2003"",""journal.title"":""Phys. Rev. E"",""doi.asserted.by"":""crossref"",""DOI"":""10.1103/PhysRevE.68.031401""},{""key"":""jp061607qb00012/jp061607qb00012_1"",""first.page"":""1297"",""volume"":""20"",""author"":""Blom A."",""year"":""2004"",""journal.title"":""Langmuir"",""doi.asserted.by"":""crossref"",""DOI"":""10.1021/la0356001""},{""key"":""jp061607qb00013/jp061607qb00013_1"",""first.page"":""16752"",""volume"":""108"",""author"":""Kawasaki H."",""year"":""2004"",""journal.title"":""J. Phys. Chem. B""},{""key"":""jp061607qb00014/jp061607qb00014_1"",""first.page"":""3219"",""volume"":""105"",""author"":""Bagchi B."",""year"":""2005"",""journal.title"":""Chem. Rev."",""doi.asserted.by"":""crossref"",""DOI"":""10.1021/cr020661+""},{""key"":""jp061607qb00015/jp061607qb00015_1"",""first.page"":""1186"",""volume"":""21"",""author"":""Ouarti N."",""year"":""2005"",""journal.title"":""Langmuir""},{""key"":""jp061607qb00016/jp061607qb00016_1"",""first.page"":""714"",""volume"":""45"",""author"":""Wilson E. B."",""year"":""1934"",""journal.title"":""J. Phys. Rev.""},{""key"":""jp061607qb00017/jp061607qb00017_1"",""first.page"":""184"",""volume"":""52"",""author"":""Lee A. S. L."",""year"":""1996"",""journal.title"":""Spectrochim. Acta, Part A"",""issue"":""2""},{""key"":""jp061607qb00018/jp061607qb00018_1"",""first.page"":""1893"",""volume"":""15"",""author"":""Korman C. S."",""year"":""1977"",""journal.title"":""Phys. Rev. B"",""doi.asserted.by"":""crossref"",""DOI"":""10.1103/PhysRevB.15.1877"",""issue"":""4""},{""key"":""jp061607qb00019/jp061607qb00019_1"",""first.page"":""8487"",""volume"":""98"",""author"":""Kwon Y. J."",""year"":""1994"",""journal.title"":""J. Phys. Chem."",""issue"":""34""},{""key"":""jp061607qb00020/jp061607qb00020_1"",""first.page"":""4416"",""volume"":""77"",""author"":""Moskovits M."",""year"":""1982"",""journal.title"":""J. Chem. Phys."",""doi.asserted.by"":""crossref"",""DOI"":""10.1063/1.444442"",""issue"":""9""},{""key"":""jp061607qb00021/jp061607qb00021_1"",""first.page"":""5046"",""volume"":""89"",""author"":""Gao P."",""year"":""1985"",""journal.title"":""J. Phys. Chem."",""doi.asserted.by"":""crossref"",""DOI"":""10.1021/j100269a032""},{""key"":""jp061607qb00022/jp061607qb00022_1"",""first.page"":""1423"",""volume"":""99"",""author"":""Lewandowski W."",""year"":""2005"",""journal.title"":""J. Inorg. Biochem."",""doi.asserted.by"":""crossref"",""DOI"":""10.1016/j.jinorgbio.2005.04.010"",""issue"":""7""},{""key"":""jp061607qb00023/jp061607qb00023_1"",""first.page"":""148"",""volume"":""29"",""author"":""Suh J. S."",""year"":""1998"",""journal.title"":""J. Raman Spectrosc."",""issue"":""2""},{""key"":""jp061607qb00024/jp061607qb00024_1"",""first.page"":""2166"",""volume"":""358"",""author"":""Lewandowski W."",""year"":""2005"",""journal.title"":""Inorg. Chim. Acta"",""doi.asserted.by"":""crossref"",""DOI"":""10.1016/j.ica.2004.10.035"",""issue"":""7""},{""key"":""jp061607qb00025/jp061607qb00025_1"",""first.page"":""9961"",""volume"":""19"",""author"":""Srinivasan V."",""year"":""2003"",""journal.title"":""Langmuir""},{""key"":""jp061607qb00026/jp061607qb00026_1"",""first.page"":""840"",""volume"":""21"",""author"":""Rakitin A. R."",""year"":""2005"",""journal.title"":""Langmuir"",""doi.asserted.by"":""crossref"",""DOI"":""10.1021/la048818b""},{""key"":""jp061607qb00027/jp061607qb00027_1"",""first.page"":""4454"",""volume"":""4447"",""author"":""Subramanian V."",""year"":""2000"",""journal.title"":""Langmuir""},{""key"":""jp061607qb00028/jp061607qb00028_1"",""unstructured"":""Chaal, L. Caractérisation d'un composé tensioactif réducteur de frottement hydrodynamique et application à l‘inhibition de l‘érosion-corrosion du cuivre en présence d‘écoulements forts. Ph.D. Thesis, University P. and M. Curie, Paris, France, December 2005.""},{""key"":""jp061607qb00029/jp061607qb00029_1"",""first.page"":""8233"",""volume"":""21"",""author"":""Poulard C."",""year"":""2005"",""journal.title"":""Langmuir""},{""key"":""jp061607qb00030/jp061607qb00030_1"",""first.page"":""494"",""volume"":""282"",""author"":""Okubo T."",""year"":""2004"",""journal.title"":""Colloid Polym. Sci.""},{""key"":""jp061607qb00031/jp061607qb00031_1"",""first.page"":""156"",""volume"":""16"",""author"":""Magid L. J."",""year"":""2000"",""journal.title"":""Langmuir""},{""key"":""jp061607qb00032/jp061607qb00032_1"",""first.page"":""6727"",""volume"":""104"",""author"":""Magid L. J."",""year"":""2000"",""journal.title"":""J. Phys. Chem. B"",""doi.asserted.by"":""crossref"",""DOI"":""10.1021/jp994477c""},{""key"":""jp061607qb00033/jp061607qb00033_1"",""first.page"":""9945"",""volume"":""19"",""author"":""Srinivasan V."",""year"":""2003"",""journal.title"":""Langmuir""}]",,,,,

In [6]:
with open("file_uniq.csv", "r") as file:
    lines = file.readlines()
    print(lines[480])  # Python is zero-indexed; line 480 is lines[479]

853.0,854,Chaos: An Interdisciplinary Journal of Nonlinear Science,2006-10-12,2023-08-01,2006-12-01,10.1063/1.2345027,2023-08-01,2006-10-11,317,10.1063,AIP Publishing,8.740883,Crossref,19,19,1,Anomalous transport fluctuations in a model of irregular media,journal-article,http://dx.doi.org/10.1063/1.2345027,"[{""given"":""O."",""family"":""Ourrad"",""sequence"":""first"",""affiliation1.name"":""Centre de Physique Théorique , CNRS–Luminy, Case 907 F-13288 Marseille, Cedex 9, France and Laboratoire de Physique Théorique, , Route de Targa Ouzemmour, 06000 Béjaia, Algeria"",""affiliation2.name"":""Université A. Mira , CNRS–Luminy, Case 907 F-13288 Marseille, Cedex 9, France and Laboratoire de Physique Théorique, , Route de Targa Ouzemmour, 06000 Béjaia, Algeria""},{""given"":""G."",""family"":""Erochenkova"",""sequence"":""additional"",""affiliation.name"":""Centre de Physique Théorique , CNRS–Luminy, Case 907 F-13288 Marseille, Cedex 9, France""},{""given"":""R."",""family"":""Lima"",""sequence"":""additional"",""affiliation.name"":""Centre de Physique Théorique , CNRS–Luminy, Case 907 F-13288 Marseille, Cedex 9, France""},{""given"":""M."",""family"":""Vittot"",""sequence"":""additional"",""affiliation.name"":""Centre de Physique Théorique , CNRS–Luminy, Case 907 F-13288 Marseille, Cedex 9, France""}]","c(""https://pubs.aip.org/aip/cha/article-pdf/doi/10.1063/1.2345027/14598362/043101_1_online.pdf"", ""https://pubs.aip.org/aip/cha/article-pdf/doi/10.1063/1.2345027/14598362/043101_1_online.pdf""), c(""application/pdf"", ""unspecified""), c(""vor"", ""vor""), c(""syndication"", ""similarity-checking"")","[{""key"":""2023080102025560400_c1"",""doi.asserted.by"":""publisher"",""first.page"":""495"",""DOI"":""10.1063/1.1391450"",""article.title"":""A fractional diffusion equation for a marker in porous media"",""volume"":""11"",""year"":""2001"",""journal.title"":""Chaos""},{""key"":""2023080102025560400_c2"",""doi.asserted.by"":""publisher"",""first.page"":""297"",""DOI"":""10.1016/S0378-4371(99)00431-8"",""article.title"":""Anomalous diffusion in irregular packed beds"",""volume"":""275"",""year"":""2000"",""journal.title"":""Physica A""},{""key"":""2023080102025560400_c3"",""doi.asserted.by"":""publisher"",""first.page"":""982"",""DOI"":""10.1063/1.1796211"",""article.title"":""A fractional equation for anomalous diffusion in a randomly heterogeneous porous media"",""volume"":""14"",""year"":""2004"",""journal.title"":""Chaos""},{""key"":""2023080102025560400_c4"",""year"":""1961"",""volume.title"":""Flow of Fluids Through Porous Materials""},{""key"":""2023080102025560400_c5"",""doi.asserted.by"":""publisher"",""first.page"":""321"",""DOI"":""10.1017/S0022112059000672"",""article.title"":""A theory of dispersion in a porous medium"",""volume"":""6"",""year"":""1959"",""journal.title"":""J. Fluid Mech.""},{""key"":""2023080102025560400_c6"",""first.page"":""126"",""article.title"":""Distribution of the first positive sum for independent random variables"",""volume"":""2"",""year"":""1957"",""journal.title"":""Theor. Probab. Appl.""},{""key"":""2023080102025560400_c7"",""doi.asserted.by"":""publisher"",""first.page"":""399"",""DOI"":""10.1017/S0022112085001598"",""article.title"":""Dispersion in fixed beds"",""volume"":""154"",""year"":""1985"",""journal.title"":""J. Fluid Mech.""},{""key"":""2023080102025560400_c8"",""doi.asserted.by"":""crossref"",""first.page"":""396"",""DOI"":""10.1016/0022-0396(86)90026-4"",""article.title"":""A very singular solution of the porous media equation with absorption"",""volume"":""65"",""year"":""1986"",""journal.title"":""J. Differ. Equations""},{""key"":""2023080102025560400_c9"",""doi.asserted.by"":""publisher"",""first.page"":""1"",""DOI"":""10.1016/S0370-1573(00)00070-3"",""article.title"":""The random walk’s guide to anomalous diffusion: A fractional dynamics approach"",""volume"":""339"",""year"":""2000"",""journal.title"":""Phys. Rep.""},{""key"":""2023080102025560400_c10"",""doi.asserted.by"":""publisher"",""first.page"":""033102"",""DOI"":""10.1063/1.2179099"",""article.title"":""Quantifying transport within a porous medium over a hierarchy of length scales"",""volume"":""18"",""year"":""2006"",""journal.title"":""Phys. Fluids""},{""key"":""2023080102025560400_c11"",""doi.asserted.by"":""publisher"",""first.page"":""461"",""DOI"":""10.1016/S0370-1573(02)00331-9"",""article.title"":""Chaos, fractional kinetics, and anomalous transport"",""volume"":""371"",""year"":""2002"",""journal.title"":""Phys. Rep.""},{""key"":""2023080102025560400_c12"",""doi.asserted.by"":""crossref"",""first.page"":""429"",""DOI"":""10.1142/9789812817747_0009"",""year"":""2000"",""volume.title"":""Application of Fractional Calculus in Physics"",""author"":""Hilfer""},{""key"":""2023080102025560400_c13"",""doi.asserted.by"":""publisher"",""first.page"":""180602"",""DOI"":""10.1103/PhysRevLett.93.180602"",""article.title"":""Stochastic reaction-diffusion phenomena in porous media with nonlinear kinetics: effects of quenched porosity fluctuations"",""volume"":""93"",""year"":""2004"",""journal.title"":""Phys. Rev. Lett.""},{""key"":""2023080102025560400_c14"",""doi.asserted.by"":""publisher"",""first.page"":""2029"",""DOI"":""10.1002/aic.690410903"",""article.title"":""Wave model for longitudinal dispersion: Development of the Model"",""volume"":""41"",""year"":""1995"",""journal.title"":""AIChE J.""},{""key"":""2023080102025560400_c15"",""doi.asserted.by"":""publisher"",""first.page"":""994"",""DOI"":""10.1063/1.1721815"",""article.title"":""Statistical hydrodynamics in porous media"",""volume"":""25"",""year"":""1954"",""journal.title"":""J. Appl. Phys.""},{""key"":""2023080102025560400_c16"",""article.title"":""Lectures: (i) A generalized theory of hydrodynamic dispersion. (ii) The optimal yield of an aquifer"",""year"":""1967"",""volume.title"":""Symposium on Artificial Recharge and Management of Aquifers of the International Association of Scientific Hydrology at Haifa, Israel""},{""key"":""2023080102025560400_c17"",""doi.asserted.by"":""crossref"",""first.page"":""901"",""DOI"":""10.1029/WR016i005p00901"",""article.title"":""Is transport in porous media always diffusive? A counter-example"",""volume"":""16"",""year"":""1980"",""journal.title"":""Water Resour. Res.""},{""key"":""2023080102025560400_c18"",""doi.asserted.by"":""publisher"",""first.page"":""7183"",""DOI"":""10.1103/PhysRevB.28.7183"",""article.title"":""Diffusion on a random lattice: weak disorder expansion in arbitrary dimension"",""volume"":""28"",""year"":""1983"",""journal.title"":""Phys. Rev. B""},{""key"":""2023080102025560400_c19"",""doi.asserted.by"":""publisher"",""first.page"":""563"",""DOI"":""10.1016/0378-4371(78)90198-X"",""article.title"":""Formulae of differentiation and their use for solving stochastic equations"",""volume"":""91"",""year"":""1978"",""journal.title"":""Physica A""}]",,,,,

In [10]:
data_cleaned = pd.read_csv("file_uniq.csv", on_bad_lines='skip' ,  index_col=0)
print(data_cleaned.head())

             Unnamed: 0                                    container.title  \
Unnamed: 0.1
0.0                   1                                               Race
2.0                   3                    The Journal of Chemical Physics
3.0                   4                    Journal of Mathematical Physics
5.0                   6                       Journal of Palestine Studies
7.0                   8  Annals of Clinical Biochemistry: International...

                 created   deposited published.print  \
Unnamed: 0.1
0.0           2008-03-29  2021-01-24         1965-04
2.0           2004-02-04  2024-02-09      1969-01-15
3.0           2004-02-10  2024-02-07      1970-07-01
5.0           2012-09-12  2021-02-13      1971-10-01
7.0           2014-02-05  2022-03-25         1978-01

                                     doi     indexed      issued member  \
Unnamed: 0.1
0.0           10.1177/030639686500600401  2022-04-03     1965-04    179
2.0                    10.1063/1.1671082  2024-02-09  1969-01-15    317
3.0                    10.1063/1.1665375  2024-07-02  1970-07-01    317
5.0                      10.2307/2535999  2022-04-03  1971-10-01    301
7.0           10.1177/000456327801500135  2022-03-31     1978-01    179

               prefix  ...             type  \
Unnamed: 0.1           ...
0.0           10.1177  ...  journal-article
2.0           10.1063  ...  journal-article
3.0           10.1063  ...  journal-article
5.0            10.108  ...  journal-article
7.0           10.1177  ...  journal-article

                                                       url  \
Unnamed: 0.1
0.0           http://dx.doi.org/10.1177/030639686500600401
2.0                    http://dx.doi.org/10.1063/1.1671082
3.0                    http://dx.doi.org/10.1063/1.1665375
5.0                      http://dx.doi.org/10.2307/2535999
7.0           http://dx.doi.org/10.1177/000456327801500135

                                                         author  \
Unnamed: 0.1
0.0           [{"given":"Patrick","family":"Duncan","sequenc...
2.0           [{"given":"J.","family":"Fourny","sequence":"f...
3.0           [{"given":"B.","family":"Picinbono","sequence"...
5.0           [{"given":"William B.","family":"Quandt","sequ...
7.0           [{"given":"D.","family":"Allard","sequence":"f...

                                                           link  \
Unnamed: 0.1
0.0           c("http://journals.sagepub.com/doi/pdf/10.1177...
2.0           c("https://pubs.aip.org/aip/jcp/article-pdf/50...
3.0           c("https://pubs.aip.org/aip/jmp/article-pdf/11...
5.0           c("http://online.ucpress.edu/jps/article-pdf/1...
7.0           c("http://journals.sagepub.com/doi/pdf/10.1177...

                                                      reference issn issue  \
Unnamed: 0.1
0.0           [{"key":"atypb1","volume.title":"House of Asse...  NaN   NaN
2.0           [{"key":"2024020904355486600_r1"},{"key":"2024...  NaN   NaN
3.0           [{"key":"2024020706263321400_r1"},{"key":"2024...  NaN   NaN
5.0           [{"key":"CIT0001","unstructured":"New York Tim...  NaN   NaN
7.0           [{"key":"bibr1-000456327801500135","first.page...  NaN   NaN

             volume page language
Unnamed: 0.1
0.0             NaN  NaN      NaN
2.0             NaN  NaN      NaN
3.0             NaN  NaN      NaN
5.0             NaN  NaN      NaN
7.0             NaN  NaN      NaN

[5 rows x 27 columns]

C:\Users\Sohaila\AppData\Local\Temp\ipykernel_25488\2853402205.py:1: DtypeWarning: Columns (9,10,12,14,15,16,21,23,24,25,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  data_cleaned = pd.read_csv("file_uniq.csv", on_bad_lines='skip' ,  index_col=0)

In [11]:
# Attempt to read all rows (may fail due to bad lines)
try:
    original_data = pd.read_csv("file_uniq.csv")
except Exception as e:
    print(f"Error reading the full dataset: {e}")

# Read the data while skipping bad lines
cleaned_data = pd.read_csv("file_uniq.csv", on_bad_lines='skip')

# Calculate the number of bad lines
total_lines = sum(1 for line in open("file_uniq.csv")) - 1  # Subtract header
cleaned_lines = len(cleaned_data)
bad_lines_count = total_lines - cleaned_lines

print(f"Total lines in the file: {total_lines}")
print(f"Lines successfully read: {cleaned_lines}")
print(f"Number of bad lines: {bad_lines_count}")

Error reading the full dataset: Error tokenizing data. C error: Expected 28 fields in line 480, saw 47

C:\Users\Sohaila\AppData\Local\Temp\ipykernel_25488\939358952.py:8: DtypeWarning: Columns (9,10,12,14,15,16,21,23,24,25,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  cleaned_data = pd.read_csv("file_uniq.csv", on_bad_lines='skip')

Total lines in the file: 315669
Lines successfully read: 309868
Number of bad lines: 5801

In [12]:
cleaned_data.to_csv("final_cleaned_data.csv")

In [15]:
data_fin_cleaned = pd.read_csv("final_cleaned_data.csv")
data_fin_cleaned.head()

C:\Users\Sohaila\AppData\Local\Temp\ipykernel_25488\588493829.py:1: DtypeWarning: Columns (10,11,13,15,16,17,22,24,25,26,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  data_fin_cleaned = pd.read_csv("final_cleaned_data.csv")

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,container.title,created,deposited,published.print,doi,indexed,issued,...,type,url,author,link,reference,issn,issue,volume,page,language
0,0,0.0,1,Race,2008-03-29,2021-01-24,1965-04,10.1177/030639686500600401,2022-04-03,1965-04,...,journal-article,http://dx.doi.org/10.1177/030639686500600401,"[{""given"":""Patrick"",""family"":""Duncan"",""sequenc...","c(""http://journals.sagepub.com/doi/pdf/10.1177...","[{""key"":""atypb1"",""volume.title"":""House of Asse...",NaN,NaN,NaN,NaN,NaN
1,1,2.0,3,The Journal of Chemical Physics,2004-02-04,2024-02-09,1969-01-15,10.1063/1.1671082,2024-02-09,1969-01-15,...,journal-article,http://dx.doi.org/10.1063/1.1671082,"[{""given"":""J."",""family"":""Fourny"",""sequence"":""f...","c(""https://pubs.aip.org/aip/jcp/article-pdf/50...","[{""key"":""2024020904355486600_r1""},{""key"":""2024...",NaN,NaN,NaN,NaN,NaN
2,2,3.0,4,Journal of Mathematical Physics,2004-02-10,2024-02-07,1970-07-01,10.1063/1.1665375,2024-07-02,1970-07-01,...,journal-article,http://dx.doi.org/10.1063/1.1665375,"[{""given"":""B."",""family"":""Picinbono"",""sequence""...","c(""https://pubs.aip.org/aip/jmp/article-pdf/11...","[{""key"":""2024020706263321400_r1""},{""key"":""2024...",NaN,NaN,NaN,NaN,NaN
3,3,5.0,6,Journal of Palestine Studies,2012-09-12,2021-02-13,1971-10-01,10.2307/2535999,2022-04-03,1971-10-01,...,journal-article,http://dx.doi.org/10.2307/2535999,"[{""given"":""William B."",""family"":""Quandt"",""sequ...","c(""http://online.ucpress.edu/jps/article-pdf/1...","[{""key"":""CIT0001"",""unstructured"":""New York Tim...",NaN,NaN,NaN,NaN,NaN
4,4,7.0,8,Annals of Clinical Biochemistry: International...,2014-02-05,2022-03-25,1978-01,10.1177/000456327801500135,2022-03-31,1978-01,...,journal-article,http://dx.doi.org/10.1177/000456327801500135,"[{""given"":""D."",""family"":""Allard"",""sequence"":""f...","c(""http://journals.sagepub.com/doi/pdf/10.1177...","[{""key"":""bibr1-000456327801500135"",""first.page...",NaN,NaN,NaN,NaN,NaN

In [22]:
data_fin_cleaned = data_fin_cleaned.drop(columns = ["Unnamed: 0.2" , "Unnamed: 0.1" , "Unnamed: 0"])

In [23]:
print(data_fin_cleaned.columns)

Index(['container.title', 'created', 'deposited', 'published.print', 'doi',
       'indexed', 'issued', 'member', 'prefix', 'publisher', 'score', 'source',
       'reference.count', 'references.count', 'is.referenced.by.count',
       'title', 'type', 'url', 'author', 'link', 'reference', 'issn', 'issue',
       'volume', 'page', 'language'],
      dtype='object')

In [24]:
size_data_cl = len(data_fin_cleaned) 
print(size_data_cl)

309868

In [25]:
unique_dois = data_fin_cleaned["doi"].unique()
num_unique_dois = len(unique_dois)
print(num_unique_dois)

309657

In [27]:
# Attempt to read all rows (may fail due to bad lines)
try:
    original_data = pd.read_csv("file_uniq_2.csv")
except Exception as e:
    print(f"Error reading the full dataset: {e}")

# Read the data while skipping bad lines
cleaned_data = pd.read_csv("file_uniq_2.csv", on_bad_lines='skip')

# Calculate the number of bad lines
total_lines = sum(1 for line in open("file_uniq_2.csv")) - 1  # Subtract header
cleaned_lines = len(cleaned_data)
bad_lines_count = total_lines - cleaned_lines

print(f"Total lines in the file: {total_lines}")
print(f"Lines successfully read: {cleaned_lines}")
print(f"Number of bad lines: {bad_lines_count}")

Error reading the full dataset: Error tokenizing data. C error: Expected 28 fields in line 214, saw 44

Total lines in the file: 7242
Lines successfully read: 7190
Number of bad lines: 52

In [26]:
data_cleaned = pd.read_csv("file_uniq_2.csv")
data_cleaned.head()

ParserError: Error tokenizing data. C error: Expected 28 fields in line 214, saw 44

In [ ]:
algeria = pd.read_csv("countries_data\papers_data_from_rcrossref_Algeria_cleaned.csv")
algeria.head()

,Unnamed: 0.1,Unnamed: 0,container.title,created,deposited,published.print,doi,indexed,issued,member,...,source,reference.count,references.count,is.referenced.by.count,title,type,url,author,link,reference
0,0,1,Race,2008-03-29,2021-01-24,1965-04,10.1177/030639686500600401,2022-04-03,1965-04,179,...,Crossref,1,1,0,Is apartheid an Insoluble Problem ?,journal-article,http://dx.doi.org/10.1177/030639686500600401,"[{""given"":""Patrick"",""family"":""Duncan"",""sequenc...","c(""http://journals.sagepub.com/doi/pdf/10.1177...","[{""key"":""atypb1"",""volume.title"":""House of Asse..."
1,2,3,The Journal of Chemical Physics,2004-02-04,2024-02-09,1969-01-15,10.1063/1.1671082,2024-02-09,1969-01-15,317,...,Crossref,7,7,22,High-Temperature Dependence of Electron and Ho...,journal-article,http://dx.doi.org/10.1063/1.1671082,"[{""given"":""J."",""family"":""Fourny"",""sequence"":""f...","c(""https://pubs.aip.org/aip/jcp/article-pdf/50...","[{""key"":""2024020904355486600_r1""},{""key"":""2024..."
2,3,4,Journal of Mathematical Physics,2004-02-10,2024-02-07,1970-07-01,10.1063/1.1665375,2024-07-02,1970-07-01,317,...,Crossref,33,33,38,Photoelectron Shot Noise,journal-article,http://dx.doi.org/10.1063/1.1665375,"[{""given"":""B."",""family"":""Picinbono"",""sequence""...","c(""https://pubs.aip.org/aip/jmp/article-pdf/11...","[{""key"":""2024020706263321400_r1""},{""key"":""2024..."
3,5,6,Journal of Palestine Studies,2012-09-12,2021-02-13,1971-10-01,10.2307/2535999,2022-04-03,1971-10-01,301,...,Crossref,15,15,2,"The Middle East Conflict in US Strategy, 1970-71",journal-article,http://dx.doi.org/10.2307/2535999,"[{""given"":""William B."",""family"":""Quandt"",""sequ...","c(""http://online.ucpress.edu/jps/article-pdf/1...","[{""key"":""CIT0001"",""unstructured"":""New York Tim..."
4,7,8,Annals of Clinical Biochemistry: International...,2014-02-05,2022-03-25,1978-01,10.1177/000456327801500135,2022-03-31,1978-01,179,...,Crossref,9,9,1,Assay of Tissue Free Cystine: Application to t...,journal-article,http://dx.doi.org/10.1177/000456327801500135,"[{""given"":""D."",""family"":""Allard"",""sequence"":""f...","c(""http://journals.sagepub.com/doi/pdf/10.1177...","[{""key"":""bibr1-000456327801500135"",""first.page..."

In [29]:
algeria.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'container.title', 'created', 'deposited',
       'published.print', 'doi', 'indexed', 'issued', 'member', 'prefix',
       'publisher', 'score', 'source', 'reference.count', 'references.count',
       'is.referenced.by.count', 'title', 'type', 'url', 'author', 'link',
       'reference'],
      dtype='object')

In [30]:
algeria = algeria.drop(columns = ["Unnamed: 0.1" , "Unnamed: 0"])

In [31]:
algeria.columns

Index(['container.title', 'created', 'deposited', 'published.print', 'doi',
       'indexed', 'issued', 'member', 'prefix', 'publisher', 'score', 'source',
       'reference.count', 'references.count', 'is.referenced.by.count',
       'title', 'type', 'url', 'author', 'link', 'reference'],
      dtype='object')

In [32]:
print(len(algeria))

21030

In [35]:
# Attempt to read all rows (may fail due to bad lines)
try:
    original_data = pd.read_csv("countries_data\\file_uniq.csv")
except Exception as e:
    print(f"Error reading the full dataset: {e}")

# Read the data while skipping bad lines
cleaned_data = pd.read_csv("countries_data\\file_uniq.csv", on_bad_lines='skip')

# Calculate the number of bad lines
total_lines = sum(1 for line in open("countries_data\\file_uniq.csv")) - 1  # Subtract header
cleaned_lines = len(cleaned_data)
bad_lines_count = total_lines - cleaned_lines

print(f"Total lines in the file: {total_lines}")
print(f"Lines successfully read: {cleaned_lines}")
print(f"Number of bad lines: {bad_lines_count}")

Error reading the full dataset: Error tokenizing data. C error: Expected 23 fields in line 214, saw 39

Total lines in the file: 2524
Lines successfully read: 2486
Number of bad lines: 38

In [36]:
al_pd_cleaned = algeria.drop_duplicates(subset="doi")

In [38]:
len(algeria)

21030

In [33]:
algeria_cleaned = pd.read_csv("countries_data\file_uniq.csv")
algeria_cleaned.head()

OSError: [Errno 22] Invalid argument: 'countries_data\x0cile_uniq.csv'